#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("R2_WhereAreYou.Resource", IsApplication=true)]

namespace R2_WhereAreYou
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int r2 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int r2_512 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int r2_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int r2_sq = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int sand = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int sand_people = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int sand_people_sq = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int sand_sq = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int dashboardLayout = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int progressImage = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int track = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int tracking_text = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Dashboard = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int StartTracking = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int StopTracking = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
